### ISSUE TITLE
2.5.4 breaks tests, does not appear to fire observer

### ISSUE THREAD

**Issue by oliverlangan** [linkedin/spaniel#105] opened 2019-05-31 16:31 UTC
I have traced a newly failing test to yesterday's release of 2.5.4: pinning our dependency to 2.5.2 fixes the failure.

Details:
- Ember project
- `ember try` ignores yarn.lock file, so upgraded specified "^2.5.2" version
- tests run in chrome headless
- will work to get a reduced test case

**Comment by lynchbomb** [comment] 2019-05-31 21:02
hi @oliverlangan what is the specific failure you are seeing?

**Comment by YoranBrondsema** [comment] 2019-07-15 14:18
I can confirm, we're seeing issues too with 2.5.4. We're using the Watcher API to observe scrolls and the events are not being fired on 2.5.4. Haven't looked deeper into the reasons why, so can't say much more.

**Comment by lynchbomb** [comment] 2019-07-15 15:56
2.5.4 addresses a CPU performance bug that could cause excessive CPU usage in some browsers. With certain versions of Safari reporting a message "This webpage is using significant energy. Closing it may improve the responsiveness of your Mac."

The primary fixes included in this patch were:

- Fix exposed doc when element has zero area
- ALLOW_CACHED_SCHEDULER Flag default to true
- Handle zero-area and display: none cases
- scheduler bug fix

Under the hood spaniel is memoizing the getBoundingClientRect calls to reduce unnecessary overhead. Especially true with the ALLOW_CACHED_SCHEDULER fix; instances where a custom root is specified or a child container is being observed you must tell spaniel to invalidate. For example as in this test: https://github.com/linkedin/spaniel/blob/v2-release/test/app/index.js#L68-L100

**Comment by oliverlangan** [comment] 2019-10-30 01:17
> Under the hood spaniel is memoizing the getBoundingClientRect calls to reduce unnecessary overhead.

That is almost certainly the problem: we are trying to observe elements whose bounds may be changing.

Is there a way to opt out of that behavior?

**Comment by seanjohnson08** [comment] 2020-09-09 17:43
I've reverted the change that introduced this bug. Thanks for the report. We'll continue to try and find ways to get the performance boost of caching without the behavior changes discovered in this issue.

**Closed by seanjohnson08** 2020-09-09 17:43 UTC

**Comment by oliverlangan** [comment] 2020-09-14 19:55
Thanks for the update. We switched some time ago to the [IntersectionObserver polyfill](https://github.com/w3c/IntersectionObserver), so I don't have an easy way to verify the fix. But I do think that removing the memoization is a good solution.
